### ISSUE TITLE
looking for a simple sample code which is explained below

### ISSUE THREAD

**Issue by jradom** [Shelex/cypress-allure-plugin-example#3]
Actually, I'm interested and was looking into https://github.com/Shelex/cypress-allure-plugin sample code.  First of all, I'm very new to Cypress/Cucumber/Typescript.  We use the above combination and https://www.npmjs.com/package/cypress-cucumber-preprocessor.  Here is what I want to accomplish and understand if your plugin will work for me with minimum rewriting or adding a lot of code.
Let's say I have a feature with a step for login into some site.  Under that, I'll have a step:
cy.screenshot('login_blah').
Then another step:
somehow make a mention of a file to attach to a report (or just a text string)

When run I want on-demand screenshot I want to see attached to a step and in case of fail attach a screenshot shot also.  Then a text file for example attached too
Is that possible to do it with your plugin?  If it is it'll great if you can make a short example.  Please, let me know

Thanks a lot in advance

Jeff

**Comment by Shelex** [comment]
Closing as this repo is already an example and question itself is related to some specific case.
