### ISSUE TITLE
How to get the allure test case count, pass count, fail count 

### ISSUE THREAD

**Issue by karthikeyanalaguraja** [Shelex/cypress-allure-plugin-example#5]
I am using GitLab, kind of figuring out a way to upload the allure-* folders into AWS s3 and making sure the index.html is a static website and open for us through the cloud front.

But now I want to know the count of no test cases executed, passed, and failed so that this will be very useful. Please help with this.

**Comment by Shelex** [comment]
If you need to get that numbers for generated report - they are available in `allure-report/widgets/summary.json` file.
If report is already hosted somewhere, you can even send a `GET` request to, for example `https://shelex.github.io/cypress-allure-plugin-example/allure-report/widgets/summary.json` and receive a response with counters.

Hope that would help.
